lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 2592000

    token_extractors:
        authorization_header:
            enabled: false
        split_cookie:
            enabled: true
            cookies: 
                - jwt_hp
                - jwt_s
    set_cookies:
        jwt_hp:
            lifetime: null
            samesite: strict
            path: /
            domain: null
            httpOnly: false
            secure: true
            split:
                - header
                - payload
        
        jwt_s:
            lifetime: 0
            samesite: strict
            path: /
            domain: null
            httpOnly: true
            secure: true
            split:
                - signature
