# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: 
        _controller: nelmio_api_doc.controller.swagger_json

# Swagger UI interface
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Alternative: Redocly interface (optionnel)
app.redocly:
    path: /api/redoc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }
