import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({ 
    subsets: ["latin"] ,
    weight: [
        "400",
        "500",
        "600",
        "700"
    ]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = {
  leftItems: [
    {
      type: 'logo',
      label: 'Tickify',
      url: '/'
    },
    {
      type: 'dropdown',
      label: 'Projets',
      dropdownItems: [
        {
          label: 'Quizify',
          url: '/project/1'
        }
      ]
    },
    {
      label: 'Créer'
    }
  ],
  rightItems : [
    {
      type: 'search',
      placeholder: 'Rechercher',
      icon: {
        src: '/images/navbar/search.svg',
        alt: 'search',
        width: 26,
        height: 26
      }
    },
    {
      type: 'avatar',
      dropdownItems: [
        {
          label: 'Mon profil',
          url: '/profile'
        },
        {
          label: 'Paramètres',
          url: '/settings'
        },
        {
          label: 'Déconnexion',
          url: '/logout'
        }
      ],
      icon: {
        src: '/images/navbar/avatar.svg',
        alt: 'avatar',
        width: 40,
        height: 40
      }
    }
  ]
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className}`}>
        <div className={`w-screen h-screen fixed top-0 left-0 bg-linear-gradient `}></div>
        <section className="w-screen h-screen backdrop-blur-lg px-6">
          <div className="flex flex-col h-full w-full">
            <Navbar items={navItems} />
            <div className={`h-full w-full`}>
              {children}
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
